###
# @name ListPhoneNumbers
GET http://localhost:54321/functions/v1/phone-numbers
Authorization: Bearer {{supabase_token}}

###
# @name GetPhoneNumberById
# @prompt id ID du numéro de téléphone à récupérer
GET http://localhost:54321/functions/v1/phone-numbers/{{id}}
Authorization: Bearer {{supabase_token}}

###
# @name SearchAvailablePhoneNumbers
POST http://localhost:54321/functions/v1/phone-numbers/search
Content-Type: application/json
Authorization: Bearer {{supabase_token}}

{
  "countryCode": "FR",
  "areaCode": "33"
}

###
# @name PurchasePhoneNumber
POST http://localhost:54321/functions/v1/phone-numbers/purchase
Content-Type: application/json
Authorization: Bearer {{supabase_token}}

{
  "phoneNumber": "+33123456789"
}

###
# @name AssignPhoneNumber
# @prompt phone_id ID du numéro de téléphone à assigner
# @prompt assistant_id ID de l'assistant à assigner au numéro
POST http://localhost:54321/functions/v1/phone-numbers/{{phone_id}}/assign
Content-Type: application/json
Authorization: Bearer {{supabase_token}}

{
  "assistantId": "{{assistant_id}}"
}

###
# @name UnassignPhoneNumber
# @prompt phone_id ID du numéro de téléphone à désassigner
DELETE http://localhost:54321/functions/v1/phone-numbers/{{phone_id}}/assign
Authorization: Bearer {{supabase_token}}

###
# @name ReleasePhoneNumber
# @prompt phone_id ID du numéro de téléphone à libérer
DELETE http://localhost:54321/functions/v1/phone-numbers/{{phone_id}}
Authorization: Bearer {{supabase_token}} 